

export const GET_ALL_BLOGS= "GET_ALL_BLOGS" 
export const LOGIN_USER="LOGIN_USER"
export const CREATE_BLOG="CREATE_BLOG"
export const EDITE_BLOG="EDITE_BLOG"
export const GET_BLOG_BY_ID="GET_BLOG_BY_ID"
export const DELETE_BLOG="DELETE_BLOG"
export const UPDATE_BLOG="UPDATE_BLOG"
export const GET_BLOG_BY_CANONICAL="GET_BLOG_BY_CANONICAL"




